name: ampcombi
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aria2=1.36.0
  - boost-cpp=1.74.0
  - bzip2=1.0.8
  - c-ares=1.34.3
  - ca-certificates=2024.8.30
  - diamond=2.0.15
  - gawk=5.3.1
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - gmp=6.3.0
  - icu=70.1
  - ld_impl_linux-64=2.43
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgomp=14.2.0
  - libiconv=1.17
  - libidn2=2.3.7
  - libnsl=2.0.1
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libxml2=2.10.3
  - libzlib=1.2.13
  - mmseqs2=15.6f452
  - mpfr=4.2.1
  - ncurses=6.5
  - openssl=3.3.2
  - perl=5.32.1
  - pip=24.3.1
  - python=3.11.0
  - readline=8.2
  - setuptools=75.3.0
  - tk=8.6.13
  - tzdata=2024b
  - wget=1.21.4
  - wheel=0.45.0
  - xz=5.2.6
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - ampcombi==2.0.0
      - biopython==1.80
      - certifi==2024.8.30
      - charset-normalizer==3.4.0
      - colorama==0.4.6
      - idna==3.10
      - iniconfig==2.0.0
      - joblib==1.4.2
      - numpy==1.26.4
      - packaging==24.2
      - pandas==1.5.2
      - pluggy==1.5.0
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - requests==2.32.3
      - six==1.16.0
      - urllib3==2.2.3