from distutils.core import setup

setup(
    name='Ampcombi_test',
    version='0.1.0',
    author='Anan Ibrahim and Louisa Perelo',
    author_email='ananhamido@hotmail.com and louisa.perelo@gmail.com',
    packages=['ampcombi'],
    scripts=['ampcombi/ampcombi.py',
             'ampcombi/amp_database.py',
             'ampcombi/amp_fasta.py',
             'ampcombi/check_input.py',
             'ampcombi/diamond_alignment.sh',
             'ampcombi/diamond_makedb.sh',
             'ampcombi/reformat_tables.py'],
    url='http://pypi.python.org/pypi/AMPcombi/',
    license='LICENSE.txt',
    description='A parsing tool for AMP tools.',
    long_description=open('README.md').read(),
   #install_requires=[
   #    "biopython",
   #    "boost-cpp",
   #    "brotlipy",
   #    "bzip2",
   #    "ca-certificates",
   #    "certifi",
   #    "cffi",
   #    "charset-normalizer",
   #    "cryptography",
   #    "diamond",
   #    "et_xmlfil",
   #    "icu",
   #    "idna",
   #    "libblas",
   #    "libcblas",
   #    "libcxx",
   #    "libffi",
   #    "libgfortran",
   #    "libgfortran5",
   #    "liblapack",
   #    "libopenblas",
   #    "libsqlite",
   #    "libzlib",
   #    "llvm-openmp",
   #    "ncurses",
   #    "numpy",
   #    "openpyxl",
   #    "openssl",
   #    "pandas",
   #    "pip",
   #    "pycparser",
   #    "pyopenssl",
   #    "pysocks",
   #    "python",
   #    "python-dateutil",
   #    "python_abi",
   #    "pytz",
   #    "readline",
   #    "requests",
   #    "setuptools",
   #    "six",
   #    "tk",
   #    "tzdata",
   #    "urllib3",
   #    "wheel",
   #    "xz",
   #    "zlib",
   #    "zstd",
   #],
    entry_points={  
        'console_scripts': [
            'ampcombi = ampcombi:main',
        ],
},
)