---
title: "AMPsummary"
authors: "Anan Ibrahim and Louisa Perelo"
output: 
  flexdashboard::flex_dashboard:
    theme:
      bg: "#101010"
      fg: "#FDF7F7" 
      primary: "#4CB963"
      base_font:
        google: Prompt
      code_font:
        google: JetBrains Mono
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r global, include=FALSE}
library("flexdashboard")
library("dplyr")
library("DT")
library("optparse")
library("htmlwidgets")
library("VennDiagram")
library("eulerr")
library("shiny")
library("knitr")
library("grid")
library("gridExtra")
library("plotly")
library("ggplot2")
library("heatmaply")
library("data.table")

# load data in 'global' chunk so it can be shared by all users of the dashboard
#load summary.csv globally
amp_summary <- data.frame(readr::read_csv("AMPcombi_summary.csv",show_col_types = FALSE)) 
#rename activities
amp_summary$Activity[amp_summary$Activity == "Not found"] <- 'Activity unknown'
amp_summary$Activity[amp_summary$Activity =="Unknown"] <- 'Activity unknown'
amp_summary$Activity[is.na(amp_summary$Activity)] <- 'Not found in reference db'

#get the names of the tools' probability columns
toMatch <- c('prob_', 'evalue_hmmer')
tool_cols <- grep(paste(toMatch,collapse="|"), colnames(amp_summary)) #list of matching col-indices 
```

Summary Table
=======================================================================
Column
-----------------------------------------------------------------------
### Interactive AMP Summary Table (all samples)
```{r echo=FALSE, message=FALSE}
DT::datatable(amp_summary, class = 'cell-border stripe',     ## add column border
          options = list( paging = TRUE,    ## paginate the output
                          pageLength = 20, ## number of rows to output for each page
                          scrollX = TRUE,   ## enable scrolling on X axis
                          scrollY = TRUE,   ## enable scrolling on Y axis
                          autoWidth = TRUE, ## use smart column width handling
                          #width = 100,
                          #height=100,
                          server = FALSE,   ## use client-side processing only load the 100 on display
                          dom = 'Bfrtip',
                          language = list(sSearch = "Keyword look-up:"),
                          #bordered = TRUE,
                          buttons = c('csv', 'excel'), ## the user can just download what on display because server=TRUE
                          columnDefs = list(list(targets = '_all', className = 'dt-center'),
                                            list(targets='aa_sequence', visible=TRUE, width='20'))),
          extensions = 'Buttons',
          selection = 'multiple',         ## enable selection of a single row
          filter = 'top',                 ## include column filters at the bottom
          rownames = FALSE                ## don't show row numbers/names)
)

```


VennDiagram
=======================================================================

Column {.sidebar}
-----------------------------------------------------------------------

Select samples and tools to be displayed

```{r}

samples = c(unique(amp_summary[["name"]]))
selectInput(inputId='sample_venn', label='Sample', choices=c(samples),  multiple=TRUE, selected=samples)

tools = colnames(amp_summary[tool_cols])
checkboxGroupInput(inputId='tool_venn',label='Tools: \n select 2-5 tools from the list', choices=c(tools), selected = tools[1:2])
```

Column
-----------------------------------------------------------------------

### VennDiagram
```{r echo=FALSE, message=FALSE, results='show'}

  # get only relevant columns from input csv
  df_venn <- amp_summary[,c(1,2,tool_cols)]
  # transform probabilites of AMPs to presence (1) and absence (0)
  df_venn[,tool_cols] <- replace(df_venn[,tool_cols], df_venn[,tool_cols]>0, 1)
  # filter df according to selected columns
  venn_df <- reactive({df_venn[df_venn$name %in% input$sample_venn, c('name','contig_id', input$tool_venn)]})
  # get number of selected tools
  venn_num <- reactive({length(input$tool_venn)})
  # get the selected tool column names
  tcols <- reactive({input$tool_venn})
  
  venn1 = reactive({venn_num()>=1})
  venn2 = reactive({venn_num()>=2})
  venn3 = reactive({venn_num()>=3})
  venn4 = reactive({venn_num()>=4})
  venn5 = reactive({venn_num()==5})
  
renderPlot({
  # create VENN diagram inputs, depending on number of tool outputs chosen
  if (venn1()==TRUE){
    A = reactive({venn_df()[,tcols()][1]})
  }
  if (venn2()==TRUE){
    B = reactive({venn_df()[,tcols()][2]})
  }
  if (venn3()==TRUE){
    C = reactive({venn_df()[,tcols()][3]})
  }
  if (venn4()==TRUE){
    D = reactive({venn_df()[,tcols()][4]})
  }
  if (venn5()==TRUE){
    E = reactive({venn_df()[,tcols()][5]})
  }
  
  # single Venn
  if (venn_num() ==1){
    grid.newpage()
    venn.plot <- draw.single.venn(sum(A()), 
                    colnames(venn_df()[0,tcols()[1:venn_num()]]),
                    fill = c("orange"),
                    filename = NULL)
    grid.draw(venn.plot)
  }
  # pairwise Venn
  if (venn_num() ==2){
    grid.newpage()
    venn.plot <- draw.pairwise.venn(area1 = sum(A()),
                    area2 = sum(B()),
                    cross.area = sum(A() == 1 & B() == 1),
                    category = c(colnames(venn_df()[0, tcols()[1:venn_num()]])),
                    fill = c("orange", "red"),filename = NULL,
                    cat.col = c("orange", "red")
                    )
    grid.draw(venn.plot)
  }
  # triple Venn
  if (venn_num() ==3){
    grid.newpage()
    venn.plot <- draw.triple.venn(area1 = sum(A()),
                    area2 = sum(B()),
                    area3 = sum(C()),
                    n12 = sum(A() == 1 & B() == 1),
                    n13 = sum(A() == 1 & C() == 1),
                    n23 = sum(B() == 1 & C() == 1),
                    n123 = sum(A() == 1 & B() == 1 & C() == 1),
                    category = c(colnames(venn_df()[0, tcols()[1:venn_num()]])),
                    fill = c("orange", "red", "green"),filename = NULL,
                    cat.col = c("orange", "red", "green")
                    )
    grid.draw(venn.plot)
  }
  # quadruple Venn
  if (venn_num() ==4){
    grid.newpage()
    venn.plot <- draw.quad.venn(area1 = sum(A()),
                    area2 = sum(B()),
                    area3 = sum(C()),
                    area4 = sum(D()),
                    n12 = sum(A() == 1 & B() == 1),
                    n13 = sum(A() == 1 & C() == 1),
                    n14 = sum(A() == 1 & D() == 1),
                    n23 = sum(B() == 1 & C() == 1),
                    n24 = sum(B() == 1 & D() == 1),
                    n34 = sum(C() == 1 & D() == 1),
                    n123 = sum(A() == 1 & B() == 1 & C() == 1),
                    n124 = sum(A() == 1 & B() == 1 & D() == 1),
                    n134 = sum(A() == 1 & C() == 1 & D() == 1),
                    n234 = sum(B() == 1 & C() == 1 & D() == 1),
                    n1234 = sum(A() == 1 & B() == 1 & C() == 1 & D() == 1),
                    category = c(colnames(venn_df()[0, tcols()[1:venn_num()]])),
                    fill = c("orange", "red", "green", "blue"),filename = NULL,
                    cat.col = c("orange", "red", "green", "blue")
                    )
    grid.draw(venn.plot)
  }
  # quintuple Venn
  if (venn_num() ==5){
    grid.newpage()
    venn.plot <- draw.quintuple.venn(area1 = sum(A()),
                    area2 = sum(B()),
                    area3 = sum(C()),
                    area4 = sum(D()),
                    area5 = sum(E()),
                    n12 = sum(A() == 1 & B() == 1),
                    n13 = sum(A() == 1 & C() == 1),
                    n14 = sum(A() == 1 & D() == 1),
                    n15 = sum(A() == 1 & E() == 1),
                    n23 = sum(B() == 1 & C() == 1),
                    n24 = sum(B() == 1 & D() == 1),
                    n25 = sum(B() == 1 & E() == 1),
                    n34 = sum(C() == 1 & D() == 1),
                    n35 = sum(C() == 1 & E() == 1),
                    n45 = sum(D() == 1 & E() == 1),
                    n123 = sum(A() == 1 & B() == 1 & C() == 1),
                    n124 = sum(A() == 1 & B() == 1 & D() == 1),
                    n125 = sum(A() == 1 & B() == 1 & E() == 1),
                    n134 = sum(A() == 1 & C() == 1 & D() == 1),
                    n135 = sum(A() == 1 & C() == 1 & E() == 1),
                    n145 = sum(A() == 1 & D() == 1 & E() == 1),
                    n234 = sum(B() == 1 & C() == 1 & D() == 1),
                    n235 = sum(B() == 1 & C() == 1 & E() == 1),
                    n245 = sum(B() == 1 & D() == 1 & E() == 1),
                    n345 = sum(C() == 1 & D() == 1 & E() == 1),
                    n1234 = sum(A() == 1 & B() == 1 & C() == 1 & D() == 1),
                    n1235 = sum(A() == 1 & B() == 1 & C() == 1 & E() == 1),
                    n1245 = sum(A() == 1 & B() == 1 & D() == 1 & E() == 1),
                    n1345 = sum(A() == 1 & C() == 1 & D() == 1 & E() == 1),
                    n2345 = sum(B() == 1 & C() == 1 & D() == 1 & E() == 1),
                    n12345 = sum(A() == 1 & B() == 1 & C() == 1 & D() == 1 & E() == 1),
                    category = c(colnames(venn_df()[0, tcols()[1:venn_num()]])),
                    fill = c("orange", "red", "green", "blue", "grey"),filename = NULL,
                    cat.col = c("orange", "red", "green", "blue", "grey")
                    )
    grid.draw(venn.plot)
  }
  # if more than 5 tools are to be compared, try to draw an EULER diagram
  # the euler diagram may not be able to show all overlaps: " if the euler model can not describe all intersections the count will not be ploted."
  # https://stackoverflow.com/questions/46629193/create-5-way-venn-diagram-from-csv-file-in-r
  if (venn_num() >5){
    grid.newpage()
    set.seed(10) #this seed changes the orientation of the sets         
    venn.plot <- plot(euler(venn_df()[,tcols()]), counts = T, fontface = 1, quantities = TRUE)
    venn.plot
    }
})

```

Dotplot
=======================================================================

Column {.sidebar}
-----------------------------------------------------------------------
AMP hits detected in one or more than two tool.

```{r}
samples = c(unique(amp_summary[["name"]]))
selectInput(inputId='sample_dotplot', label='Sample_dotplot', choices=c(samples),  multiple=TRUE, selected=samples)

selectInput('xcol', 'X-axis', choices = colnames(amp_summary), selected=colnames(amp_summary['name']))
selectInput('ycol', 'Y-axis', choices = colnames(amp_summary), selected=colnames(amp_summary['Activity']))
selectInput('zcol', 'Hovering text', colnames(amp_summary), selected=colnames(amp_summary['contig_id']))

tools = colnames(amp_summary[tool_cols])
checkboxGroupInput(inputId='tool_dotplot',label='AMP Tools', choices=c(tools), selected = tools[1:2])
```

Column{data-width=700}
-----------------------------------------------------------------------

### Test dotplot

```{r echo=FALSE, message=FALSE, results='show'}
# replace 0 by 1s
amp_summary[,tool_cols] <- replace(amp_summary[,tool_cols], amp_summary[,tool_cols]>0, 1)
# make a copy of the tools
tool_df <- as.data.frame(amp_summary[,c(tools)])
# remove the amp tools from the df
amp_summary_new <- amp_summary[ , -which(names(amp_summary) %in% c(tools))]
# grab the amp tools column numbers according to tools selected 
matching <- reactive({input$tool_dotplot})
# filter the table according to the tools selected and sum the rows
subset <- reactive({data.frame(tool_df[c(matching())])})
# add the sums to the table
new_df <- reactive({data.frame(cbind(amp_summary_new, sums = rowSums(subset())))})
# grab the samples column numbers according to samples selected 
new_samples <- reactive({input$sample_dotplot})
# filter by selected samples
filtered_df <- reactive({
  new_df()[new_df()$name %in% new_samples(), ]
  })

# Interactive ggplot
renderPlotly({
# Filter by the number of tools selected
  if (length(matching()) == 1){
   df2 <- filtered_df()[filtered_df()$sums ==  1,]
  }
  if (length(matching()) == 2){
   df2 <- filtered_df()[filtered_df()$sums ==  2,]
  }
  if (length(matching()) == 3){
   df2 <- filtered_df()[filtered_df()$sums ==  3,]
  }
  if (length(matching()) == 4){
   df2 <- filtered_df()[filtered_df()$sums ==  4,]
  }
  if (length(matching()) == 5){
   df2 <- filtered_df()[filtered_df()$sums ==  5,]
  }

# Filter by the number of tools selected and the x/y/z/ axes selected
  xaxis = reactive(input$xcol) # name
  yaxis = reactive(input$ycol) # activity
  zaxis = reactive(input$zcol) # contig_id

  df_df = reactive ({
    filtered_df() %>%
      filter(sums == 2) %>%
      select(c(xaxis(), yaxis(), zaxis()))
    })

# prepare the df for concatenation of contig_id
  df_x <- reactive({unlist(unname(c(unique(df_df()[c(xaxis())]))))
    })
  df_y <- reactive({unlist(unname(c(unique(df_df()[c(yaxis())]))))
    })
  df_z <- reactive({unlist(unname(c(df_df()[c(zaxis())])))
    })

# Concatenate contig_id
  node_data <- reactive({
    noRows <- length(df_y())
    noCols <- length(df_x())
  node_mat <- data.frame(matrix(ncol = noCols, nrow = noRows, dimnames=list(df_y(), df_x())))
  for(i in 1:noCols){
      df_sub = reactive({df_df()[df_df()[c(xaxis())] == df_x()[i],]})
      for(j in 1:noRows){
        df_sub2 <- reactive(df_sub()[df_sub()[c(yaxis())] == df_y()[j],])
        contig_names <- reactive(unlist(c(df_sub2()[c(zaxis())])))
        nodes <- reactive(paste(contig_names(), collapse=", "))
        node_mat[j,i] <- nodes()
        }
   }
  return(node_mat)
  })

# format from wide to long format
  node_long_1 <- reactive(data.frame(cbind(yy=rownames(node_data()), node_data())))
  node_long_2 <- reactive({data.frame(melt(node_long_1(),id.vars="yy", variable.name="xx", value.name="zz",na.rm=T))})
# remove rows that have no yy
  df_final <- reactive(node_long_2()[!node_long_2()["zz"]=="",])

  p <- ggplot(df_final(), aes(x=xx, y=yy, color = xx, text = stringr::str_wrap(
                  string = zz,
                  width = 40,
                  indent = 1, # add extra space from the margins
                  exdent = 1  # add extra space from the margins
                ))) +
    geom_point() +
    theme(axis.text.x = element_text(face="plain", color="black",
                                     size=8, angle=60, vjust = .5, hjust = .5),
          axis.text.y = element_text(face="plain", color="black",
                                     size=8, angle=0)) +
    theme(panel.border=element_rect(colour="black",fill=NA,size=1.2),
          strip.background=element_rect(colour="black",size=1.2),
          panel.grid.major.x=element_line(size=0.5,colour="grey88"),
          panel.grid.minor.x=element_blank(),
          panel.grid.major.y=element_line(size=0.5,colour="grey88"),
          panel.background=element_rect(fill="white"),
          legend.position = "none")
  ggplotly(p, tooltip = "text")
  #text = gsub('(.{1,100})(\\s|$)', '\\1\n', zz)))
  })
renderPrint(as.character(event_data("plotly_hover")))
```

Heatmap
=======================================================================

Column {.sidebar}
-----------------------------------------------------------------------


```{r}
activities = unique(amp_summary[["Activity"]])
samples = c(unique(amp_summary[["name"]]))

selectInput(inputId='nodes_act',label='Choose one activity and sample to display contig names', choices=c(activities), selected = activities[1])
selectInput(inputId='nodes_sample', label='', choices=c(samples), selected=samples[1])

selectInput(inputId='sample_hm', label='Select samples and activities to be displayed in Heatmap: Samples', choices=c(samples),  multiple=TRUE, selected=samples)

#tools = colnames(amp_summary[tool_cols])
#checkboxGroupInput(inputId='tool_hm',label='Tools', choices=c(tools), selected = tools[1:2])

selectInput(inputId='activity_hm',label='Biological activities', choices=c(activities), multiple=TRUE, selected = activities)

```

Column{data-width=700}
-----------------------------------------------------------------------

### AMP Activity Heatmap
```{r echo=FALSE, message=FALSE, results='show'}

df <- amp_summary[,c("name","contig_id","Activity")]
s = reactive(input$sample_hm)
a = reactive(input$activity_hm)
t = reactive(input$tool_hm)
heatmap_df <- reactive({df[df$name %in% s() & df$Activity %in% a(), ]})

# prepare data for heatmap
################################

count_data <- reactive({
  noRows <- length(a())
  noCols <- length(s())
 count_mat <- data.frame(matrix(ncol = noCols, nrow = noRows, dimnames=list(a(), s())))
 for(i in 1:noCols){
    df_sub = reactive({heatmap_df()[heatmap_df()$name == s()[i],]})
    for(j in 1:noRows){
      df_sub2 <- reactive(df_sub()[df_sub()$Activity == a()[j],])
      count <- reactive(nrow(df_sub2()))
      count_mat[j,i] <- count()
      }
    }
return(count_mat)
})
#count_data

node_data <- reactive({
  noRows <- length(a())
  noCols <- length(s())
 node_mat <- data.frame(matrix(ncol = noCols, nrow = noRows, dimnames=list(a(), s())))
 for(i in 1:noCols){
    df_sub = reactive({heatmap_df()[heatmap_df()$name == s()[i],]})
    for(j in 1:noRows){
      df_sub2 <- reactive(df_sub()[df_sub()$Activity == a()[j],])
      contig_names <- reactive(df_sub2()$contig_id)
      nodes <- reactive(paste(contig_names(), collapse=", "))
      node_mat[j,i] <- nodes()
      }
    }
return(node_mat)
})
#node_data

# Heatmap
renderPlotly({
  heatmaply(count_data(),
               dendrogram = "column",
               #xlab = "Sample name", ylab = "Activity",
               #main = "",
               grid_color = "white",
               grid_width = 0.00001,
               titleX = FALSE,
               colors = hcl.colors(500, palette='viridis', alpha=NULL,rev=TRUE),
               fontsize_row = 5, fontsize_col = 5,
               #custom_hovertext = node_data(),
               heatmap_layers = theme(axis.line=element_blank())
)
})

```
Column{data-width=300}
-----------------------------------------------------------------------

### List of contigs
```{r}
nodelist <- reactive({
  sample <- input$nodes_sample
  activity <- input$nodes_act
  df_sub3 = reactive({heatmap_df()[heatmap_df()$Activity == activity & heatmap_df()$name == sample,]})
  return(df_sub3()$contig_id)
})
nodelist

```


Test histogram
=======================================================================
Column {.sidebar}
-----------------------------------------------------------------------

Waiting time between eruptions and the duration of the eruption for the
Old Faithful geyser in Yellowstone National Park, Wyoming, USA.

```{r}
selectInput("n_breaks2", label = "number of breaks",
            choices = c(10, 20, 30, 50, 100), selected = 20)

sliderInput("bw_adjust2", label = "Bandwidth adjustment:",
            min = 0.2, max = 2, value = 1, step = 0.2)

samples = c(unique(amp_summary[["name"]]))
selectInput(inputId='sample2', label='Sample', choices=samples,  multiple=TRUE, selected=samples[1])

tools = colnames(amp_summary[tool_cols])
checkboxGroupInput(inputId='tool2',label='Tools', choices=tools, selected = tools[1])
```

Column
-----------------------------------------------------------------------

### Test histogram

```{r}
renderPlot({
  df <- amp_summary[,c(1,2,tool_cols)]
  df[,tool_cols] <- replace(df[,tool_cols], df[,tool_cols]>0, 1)
  df <- df[df$name %in% input$sample2, c('name','contig_id', input$tool2)]
  
  hist(df[,input$tool2], probability = TRUE, breaks = as.numeric(input$n_breaks2),
      xlab = input$tool2, main = "Geyser Eruption Duration")
  
  #dens <- density(faithful$eruptions, adjust = input$bw_adjust)
  #lines(dens, col = "blue")
})
```