---
title: "Themed dashboard"
output: 
  flexdashboard::flex_dashboard:
    theme:
      bg: "#101010"
      fg: "#FDF7F7" 
      primary: "#4CB963"
      base_font:
        google: Prompt
      code_font:
        google: JetBrains Mono
    orientation: rows
    vertical_layout: fill
runtime: shiny
---

```{r global, include=FALSE}
library("flexdashboard")
library("dplyr")
library("DT")
library("optparse")
library("htmlwidgets")
library("VennDiagram")
library("eulerr")
library("shiny")
library("knitr")

# load data in 'global' chunk so it can be shared by all users of the dashboard
library(datasets)
data(faithful)
#load summary.csv globally
amp_summary <- data.frame(readr::read_csv("AMPcombi_summary.csv",show_col_types = FALSE)) 
#get the names of the tools' probability columns
toMatch <- c('prob_', 'evalue_hmmer')
tool_cols <- grep(paste(toMatch,collapse="|"), colnames(amp_summary)) #list of matching col-indices 
```

VennDiagram
=======================================================================

Column {.sidebar}
-----------------------------------------------------------------------

Select samples and tools to be displayed

```{r}
samples = c(unique(amp_summary[["name"]]))
selectInput(inputId='sample', label='Sample', choices=c(samples),  multiple=TRUE, selected=samples[1])

tools = colnames(amp_summary[tool_cols])
checkboxGroupInput(inputId='tool',label='Tools', choices=c(tools), selected = tools)

df <- amp_summary[,c(1,2,tool_cols)]
df[,tool_cols] <- replace(df[,tool_cols], df[,tool_cols]>0, 1)
venn_df <- reactive({
  df[df$name %in% input$sample, c('name','contig_id', input$tool)]
  })
venn_df
```

Column
-----------------------------------------------------------------------

### VennDiagram
```{r echo=FALSE, message=FALSE, results='show'}
  # df <- amp_summary[,c(1,2,tool_cols)]
  # df[,tool_cols] <- replace(df[,tool_cols], df[,tool_cols]>0, 1)
  # #venn_df <- df[df$name %in% input$sample, c('name','contig_id', input$tool)]
  # testtools = c("prob_amplify", "prob_ampir", "prob_macrel")
  # venn_df <- df[df$name %in% "ECO004-megahit", c('name','contig_id', testtools)]
  # #venn_num <- length(venn_df)-2
  # venn_num <- 3
  # drawVenn(venn_df, venn_num, testtools)

# ss <- reactive({
#        input$sample
#    })
# tt <- reactive({
#        input$tool
#    })
# tt

#   # testtools = c("prob_amplify", "prob_ampir", "prob_macrel")
#   # venn_df <- df[df$name %in% "ECO004-megahit", c('name','contig_id', testtools)]

renderPlot({
library(grid)
library(gridExtra)
# venn.plot <- draw.triple.venn(65, 75, 85,
#  35, 15, 25, 5, c("First", "Second", "Third"))

drawVenn = function(venn_df, venn_num, tools){
  tool_cols <- grep(paste(tools,collapse="|"), colnames(venn_df))
  # create VENN diagram
  if (venn_num <=0){
    print("Please select tool outputs to be visualized")
  }
  if (venn_num >=1){
    A = venn_df[,tool_cols][1]
  }
  if (venn_num >=2){
    B = venn_df[,tool_cols][2]
  }
  if (venn_num >=3){
    C = venn_df[,tool_cols][3]
  }
  if (venn_num >=4){
    D = venn_df[,tool_cols][4]
  }
  if (venn_num ==5){
    E = venn_df[,tool_cols][5]
  }
  
  # single Venn
  if (venn_num ==1){
    grid.newpage()
    venn.plot = draw.single.venn(sum(A), 
                     colnames(venn_df[0,tool_cols[1:venn_num]]),
                     fill = c("orange"))
    grid.draw(venn.plot)
    }
  # pairwise Venn
  if (venn_num ==2){
    grid.newpage()
    venn.plot =draw.pairwise.venn(area1 = sum(A),
                       area2 = sum(B),
                       cross.area = sum(A == 1 & B == 1),
                       category = c(colnames(venn_df[0, tool_cols[1:venn_num]])),
                       fill = c("orange", "red"),
                       cat.col = c("orange", "red")
                      )
    grid.draw(venn.plot)
  }
  # triple Venn
  if (venn_num ==3){
    grid.newpage()
    venn.plot = draw.triple.venn(area1 = sum(A),
                        area2 = sum(B),
                        area3 = sum(C),
                        n12 = sum(A == 1 & B == 1),
                        n13 = sum(A == 1 & C == 1),
                        n23 = sum(B == 1 & C == 1),
                        n123 = sum(A == 1 & B == 1 & C == 1),
                        category = c(colnames(venn_df[0, tool_cols[1:venn_num]])),
                        fill = c("orange", "red", "green"),
                        cat.col = c("orange", "red", "green")
    )
    grid.draw(venn.plot)
  }
  # quadruple Venn
  if (venn_num ==4){
    grid.newpage()
    draw.quad.venn(area1 = sum(A),
                        area2 = sum(B),
                        area3 = sum(C),
                        area4 = sum(D),
                        n12 = sum(A == 1 & B == 1),
                        n13 = sum(A == 1 & C == 1),
                        n14 = sum(A == 1 & D == 1),
                        n23 = sum(B == 1 & C == 1),
                        n24 = sum(B == 1 & D == 1),
                        n34 = sum(C == 1 & D == 1),
                        n123 = sum(A == 1 & B == 1 & C == 1),
                        n124 = sum(A == 1 & B == 1 & D == 1),
                        n134 = sum(A == 1 & C == 1 & D == 1),
                        n234 = sum(B == 1 & C == 1 & D == 1),
                        n1234 = sum(A == 1 & B == 1 & C == 1 & D == 1),
                        category = c(colnames(venn_df[0, tool_cols[1:venn_num]])),
                        fill = c("orange", "red", "green", "blue"),
                        cat.col = c("orange", "red", "green", "blue")
    )
    grid.draw(venn.plot)
  }
  # quintuple Venn
  if (venn_num ==5){
    grid.newpage()
    draw.quintuple.venn(area1 = sum(A),
                        area2 = sum(B),
                        area3 = sum(C),
                        area4 = sum(D),
                        area5 = sum(E),
                        n12 = sum(A == 1 & B == 1),
                        n13 = sum(A == 1 & C == 1),
                        n14 = sum(A == 1 & D == 1),
                        n15 = sum(A == 1 & E == 1),
                        n23 = sum(B == 1 & C == 1),
                        n24 = sum(B == 1 & D == 1),
                        n25 = sum(B == 1 & E == 1),
                        n34 = sum(C == 1 & D == 1),
                        n35 = sum(C == 1 & E == 1),
                        n45 = sum(D == 1 & E == 1),
                        n123 = sum(A == 1 & B == 1 & C == 1),
                        n124 = sum(A == 1 & B == 1 & D == 1),
                        n125 = sum(A == 1 & B == 1 & E == 1),
                        n134 = sum(A == 1 & C == 1 & D == 1),
                        n135 = sum(A == 1 & C == 1 & E == 1),
                        n145 = sum(A == 1 & D == 1 & E == 1),
                        n234 = sum(B == 1 & C == 1 & D == 1),
                        n235 = sum(B == 1 & C == 1 & E == 1),
                        n245 = sum(B == 1 & D == 1 & E == 1),
                        n345 = sum(C == 1 & D == 1 & E == 1),
                        n1234 = sum(A == 1 & B == 1 & C == 1 & D == 1),
                        n1235 = sum(A == 1 & B == 1 & C == 1 & E == 1),
                        n1245 = sum(A == 1 & B == 1 & D == 1 & E == 1),
                        n1345 = sum(A == 1 & C == 1 & D == 1 & E == 1),
                        n2345 = sum(B == 1 & C == 1 & D == 1 & E == 1),
                        n12345 = sum(A == 1 & B == 1 & C == 1 & D == 1 & E == 1),
                        category = c(colnames(venn_df[0, tool_cols[1:venn_num]])),
                        fill = c("orange", "red", "green", "blue", "grey"),
                        cat.col = c("orange", "red", "green", "blue", "grey")
    )
    grid.draw(venn.plot)
  }
  # if more than 5 tools are to be compared, try to draw an EULER diagram
  # the euler diagram may not be able to show all overlaps: " if the euler model can not describe all intersections the count will not be ploted."
  # https://stackoverflow.com/questions/46629193/create-5-way-venn-diagram-from-csv-file-in-r
  if (venn_num >5){
    set.seed(10) #this seed changes the orientation of the sets         
    return (plot(euler(venn_df[,tool_cols]), counts = T, fontface = 1, quantities = TRUE))
  }
}

venn_num <- length(venn_df)-2
# venn_num <- 3
drawVenn(venn_df, venn_num, input$tool)
})

#test to show that the function drawVenn works
#df <- amp_summary[,c(1,2,tool_cols)]
#df[,tool_cols] <- replace(df[,tool_cols], df[,tool_cols]>0, 1)
#testtools = c("prob_macrel", "prob_amplify", "prob_ampir")
#venn_data <- df[df$name %in% c("sample_1"), c('name','contig_id', testtools)]
#drawVenn(venn_data, 3, testtools)

```


Test histogram
=======================================================================
Column {.sidebar}
-----------------------------------------------------------------------

Waiting time between eruptions and the duration of the eruption for the
Old Faithful geyser in Yellowstone National Park, Wyoming, USA.

```{r}
selectInput("n_breaks2", label = "number of breaks",
            choices = c(10, 20, 30, 50, 100), selected = 20)

sliderInput("bw_adjust2", label = "Bandwidth adjustment:",
            min = 0.2, max = 2, value = 1, step = 0.2)

samples = c(unique(amp_summary[["name"]]))
selectInput(inputId='sample2', label='Sample', choices=samples,  multiple=TRUE, selected=samples[1])

tools = colnames(amp_summary[tool_cols])
checkboxGroupInput(inputId='tool2',label='Tools', choices=tools, selected = tools[1])
```

Column
-----------------------------------------------------------------------

### Test histogram

```{r}
renderPlot({
  df <- amp_summary[,c(1,2,tool_cols)]
  df[,tool_cols] <- replace(df[,tool_cols], df[,tool_cols]>0, 1)
  df <- df[df$name %in% input$sample2, c('name','contig_id', input$tool2)]
  
  hist(df[,input$tool2], probability = TRUE, breaks = as.numeric(input$n_breaks2),
       xlab = input$tool2, main = "Geyser Eruption Duration")
  
  #dens <- density(faithful$eruptions, adjust = input$bw_adjust)
  #lines(dens, col = "blue")
})
```