---
title: "Old Faithful Eruptions"
output: flexdashboard::flex_dashboard
runtime: shiny
---

```{r global, include=FALSE}
# load data in 'global' chunk so it can be shared by all users of the dashboard
library(datasets)
data(faithful)
#load summary.csv globally
amp_summary <- data.frame(readr::read_csv("/Users/lp1/Documents/nextflow/funcscan/ampcombi/AMPcombi_summary.csv",show_col_types = FALSE)) 
#get the names of the tools' probability columns
toMatch <- c('prob_', 'evalue_hmmer')
tool_cols <- grep(paste(toMatch,collapse="|"), colnames(amp_summary)) #list of matching col-indices 
```

Column {.sidebar}
-----------------------------------------------------------------------

Waiting time between eruptions and the duration of the eruption for the
Old Faithful geyser in Yellowstone National Park, Wyoming, USA.

```{r}
selectInput("n_breaks", label = "number of breaks",
            choices = c(10, 20, 30, 50, 100), selected = 20)

sliderInput("bw_adjust", label = "Bandwidth adjustment:",
            min = 0.2, max = 2, value = 1, step = 0.2)

samples = c(unique(amp_summary[["name"]]))
selectInput(inputId='sample', label='Sample', choices=samples,  multiple=TRUE, selected=samples[1])

tools = colnames(amp_summary[tool_cols])
checkboxGroupInput(inputId='tool',label='Tools', choices=tools, selected = tools[1])
```

Column
-----------------------------------------------------------------------

### Geyser Eruption Duration

```{r}
renderPlot({
  df <- amp_summary[,c(1,2,tool_cols)]
  df[,tool_cols] <- replace(df[,tool_cols], df[,tool_cols]>0, 1)
  df <- df[df$name %in% input$sample, c('name','contig_id', input$tool)]
  
  hist(df[,input$tool], probability = TRUE, breaks = as.numeric(input$n_breaks),
       xlab = input$tool, main = "Geyser Eruption Duration")
  
  #dens <- density(faithful$eruptions, adjust = input$bw_adjust)
  #lines(dens, col = "blue")
})
```

