#!/usr/bin/env Rscript

##############################
# Rscript to visualise the complete summary tables generated by AMPcombi ####
##############################
# Date ####
# October, 19 2022
##############################
# Authors ####
# Anan Ibrahim
# ananhamido@hotmail.com 
# @darcy220606
##############################
# Working_directory ####
##############################
setwd("/home/aibrahim/github/testing_ampcombi_on_deepevo")
##############################
# Libraries used + arguments ####
if (!require("dplyr")) install.packages('dplyr')
if (!require("DT")) install.packages('DT')
if (!require("optparse")) install.packages('optparse')

library("dplyr")
library("DT")
library("optparse")
library(htmlwidgets)
# option_list = list(
#   make_option(c("-f", "--file"), type="character", default=NULL, 
#               help="AMpcombi complete summary table", metavar="character"),
#   make_option(c("-o", "--out"), type="character", default="AMPcombi_summary.html", 
#               help="Provide the name of the output file [default= %default]", metavar="character")
# ); 
# 
# opt_parser = OptionParser(option_list=option_list);
# opt = parse_args(opt_parser);

##############################
#Generate HTML interactive files ####
table <-
  readr::read_csv("ECO004-CDC007.csv") %>%
  unique()

result<-datatable(table,
          class = 'cell-border stripe',     ## add column border
          options = list( paging = TRUE,    ## paginate the output
                          pageLength = 100, ## number of rows to output for each page
                          scrollX = TRUE,   ## enable scrolling on X axis
                          scrollY = TRUE,   ## enable scrolling on Y axis
                          autoWidth = TRUE, ## use smart column width handling
                          #width = 20,
                          server = TRUE,   ## use client-side processing only load the 100 on display
                          dom = 'Bfrtip',
                          #bordered = TRUE,
                          buttons = c('csv', 'excel'), ## the user can just download what on display because server=TRUE
                          columnDefs = list(list(targets = '_all', className = 'dt-center',width = '20px'),
                                            list(targets = c(0, 8, 9), visible = TRUE))),
          extensions = 'Buttons',
          selection = 'multiple',         ## enable selection of a single row
          filter = 'top',                 ## include column filters at the bottom
          rownames = FALSE                ## don't show row numbers/names
          )

htmlwidgets::saveWidget(result, "result.html")
##############################
