#!/usr/bin/env Rscript

#Rscript shinyapp/shinyapp_html_file.R -f ../testing_ampcombi_on_deepevo/ECO004-CDC007.csv

##############################
# Shinyapp to visualise the complete summary tables generated by AMPcombi ####
##############################
# Date ####
# October, 19 2022
##############################
# Authors ####
# Anan Ibrahim
# ananhamido@hotmail.com 
# @darcy220606
##############################
# Working_directory ####
##############################
#setwd("/home/aibrahim/github/testing_ampcombi_on_deepevo")
##############################
# Libraries used + arguments ####
library(dplyr)
library(DT)
library(shiny)
library(data.table)
library(ggplot2)
library(optparse)

option_list = list(
  make_option(c("-f", "--file"), type="character", default=NULL, 
              help="AMpcombi complete summary table", metavar="character"),
  make_option(c("-o", "--out"), type="character", default="AMPcombi_summary.html", 
              help="Provide the name of the output file [default= %default]", metavar="character")
); 

opt_parser = OptionParser(option_list=option_list);
opt = parse_args(opt_parser);

##############################
# Generate the html file ####
##############################
table <-
  readr::read_csv(opt$file) %>% 
  unique()

about_page <- tabPanel(
  title = strong('About'),
  br(),
  includeMarkdown("https://raw.githubusercontent.com/Darcy220606/AMPcombi/dev/README.md")
)
## page 2: Summary table
summary_page <- tabPanel(title = strong('Summary table'),
                         mainPanel(DTOutput('tbl'), 
                                   width = 20))
## page 3: Plots and figures
plots_page <- tabPanel(title = strong('Plots'),
                       titlePanel("Analysis"),
                       sidebarLayout(
                         sidebarPanel(
                         ),
                         mainPanel(
                           tabsetPanel(
                             tabPanel(
                               title = "Plot"
                             ),
                             tabPanel(
                               title = "Statistics",
                             )
                           )
                         )
                       ))


## Shiny app
ui <- navbarPage(
  title = strong("AMPcombi"), 
  about_page,
  summary_page,
  plots_page,
  tags$style(type = 'text/css', '.navbar { background-color: #a2d2ff;
                                               font-family: Arial;
                                               font-size: 15px;
                                               color: #023047; }')
)
server <- function(input, output)
{output$tbl = renderDT(table,
                       class = 'cell-border stripe',     ## add column border
                       options = list( paging = TRUE,    ## paginate the output
                                       pageLength = 100, ## number of rows to output for each page
                                       scrollX = TRUE,   ## enable scrolling on X axis
                                       scrollY = TRUE,   ## enable scrolling on Y axis
                                       autoWidth = TRUE, ## use smart column width handling
                                       #width = 200,
                                       server = TRUE,   ## use client-side processing only load the 100 on display
                                       dom = 'Bfrtip',
                                       #bordered = TRUE,
                                       buttons = c('csv', 'excel'), ## the user can just download what on display because server=TRUE
                                       columnDefs = list(list(targets = '_all', className = 'dt-center'),
                                                         list(targets = c(0, 8, 9), visible = TRUE))),
                       extensions = 'Buttons',
                       selection = 'multiple',         ## enable selection of a single row
                       filter = 'top',                 ## include column filters at the bottom
                       rownames = FALSE                ## don't show row numbers/names
)}
shinyApp(ui = ui, server = server)
